---
- name: Install zabbix repository.
  apt_repository:
    repo: "deb http://repo.zabbix.com/zabbix/{{ zabbix_agent_version }}/ubuntu/ {{ ansible_distribution_release }} main"

- name: Install gpg key.
  apt_key:
    url: https://repo.zabbix.com/zabbix-official-repo.key

- name: Ensure zabbix-agent is installed
  apt:
    name: zabbix-agent
    update_cache: yes
    cache_valid_time: 0
