---
# install tasks.
- include: install-{{ ansible_os_family }}.yml
  static: no

# configure
- name: Copy zabbix configuration in place.
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify:
    - restart zabbix-agent

# service
- name: Ensure zabbix-agent is started and enabled to start at boot.
  service: name=zabbix-agent state=started enabled=yes
  when: ansible_connection != 'docker'