---
# install
- name: Add multiple zabbix repositories into the same file (1/2)
  yum_repository:
    name: zabbix
    description: Zabbix Official Repository - $basearch
    baseurl: http://repo.zabbix.com/zabbix/{{ zabbix_agent_version }}/rhel/{{ ansible_distribution_major_version }}/$basearch/
    gpgcheck: no
    enabled: no
- name: Add multiple zabbix repositories into the same file (2/2)
  yum_repository:
    name: zabbix-non-supported
    description: Zabbix Official Repository non-supported - $basearch
    baseurl: http://repo.zabbix.com/non-supported/rhel/{{ ansible_distribution_major_version }}/$basearch/
    gpgcheck: no
    enabled: no

- name: Ensure zabbix is installed.
  yum: name=zabbix-agent enablerepo=zabbix

# configure
- name: Copy zabbix configuration in place.
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify:
    - restart zabbix-agent

# service
- name: Ensure zabbix-agent is started and enabled to start at boot.
  service: name=zabbix-agent state=started enabled=yes
